name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  codebuild:
    name: Run CodeBuild Job on PR
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Commitlint and Other Shared Build Steps
        uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get AssumeRole Session Name
        run: |
          env
          echo "ROLE_SESSION_NAME=${GITHUB_REPOSITORY}-${GITHUB_RUN_NUMBER}" |tr "/" "_" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_CICD_DEPLOY_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_CICD_DEPLOY_USER_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::401011790710:role/pull-request-code-build
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          role-duration-seconds: 1200

      - name: Run CodeBuild Job
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: momento-large-2021-11

